[package]
name = "matrix-hyper-federation-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
base64 = "0.21.0"
compact_str = { version = "0.7.0", features = ["serde"] }
doc-comment = "0.3.3"
ed25519-dalek = "1.0.1"
futures = "0.3.28"
futures-util = "0.3.28"
http = "0.2.9"
hyper = { version = "0.14.25", features = ["client", "http1", "server", "stream"] }
hyper-rustls = "0.24.0"
log = "0.4.17"
rand = "0.8.5"
ritelinked = "0.3.2"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
signed-json = { git = "https://github.com/erikjohnston/rust-signed-json.git" }
tokio = { version = "1.27.0", features = ["macros"] }
tokio-rustls = "0.24.0"
trust-dns-resolver = "0.22.0"
url = "2.3.1"
